version: "3"

networks:
  my-network:
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: php_login
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./db/sqliteDB.sqlite:/app/db/sqliteDB.sqlite
    networks:
      - my-network

  

