version: "3"

networks:
  my-network:
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: php_login
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - my-network

  db:
    build: # Cambiamos esto para usar el Dockerfile personalizado
      context: .
      dockerfile: postgres/Dockerfile # Asegúrate de que el Dockerfile esté configurado para inicializar la DB
    environment:
      POSTGRES_DB: php_login
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - my-network

volumes:
  postgres-data:
